[versions]
# 核心框架版本
spring-boot = "3.5.6"
spring-dependency-management = "1.1.7"

# 常用工具版本
lombok = "1.18.30"
mapstruct = "1.5.5.Final"
lombok-mapstruct-binding = "0.2.0"

[libraries]
# Spring Boot  starters
spring-boot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "spring-boot" }

# 其他常用库
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }
lombok-mapstruct-binding = { group = "org.projectlombok", name = "lombok-mapstruct-binding", version.ref = "lombok-mapstruct-binding" }

[bundles]
microservice-core = [
]

mapstruct-annotation = [
    "mapstruct-processor", "lombok-mapstruct-binding"
]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }