kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tutorial-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.32.2
  - role: worker
    image: kindest/node:v1.32.2
  - role: worker
    image: kindest/node:v1.32.2
containerdConfigPatches:
  - |-
    # Docker Hub 镜像加速
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
      endpoint = [
        "https://docker.m.daocloud.io",
        "https://docker.imgdb.de", 
        "https://docker-0.unsee.tech",
        "https://docker.hlmirror.com",
        "https://docker.1ms.run",
        "https://func.ink",
        "https://lispy.org",
        "https://docker.xiaogenban1993.com"
      ]